# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNumeros():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_numeros(self):
    self.driver.get("http://127.0.0.1/fernandezt1/formulario.html")
    self.driver.set_window_size(1050, 700)
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "nombre").send_keys("4567")
    self.driver.find_element(By.ID, "apellido").send_keys("45678")
    self.driver.find_element(By.ID, "email").send_keys("123546")
    self.driver.find_element(By.ID, "password").send_keys("q3456")
    self.driver.find_element(By.ID, "repetir").send_keys("23544576utf")
    self.driver.find_element(By.ID, "fecha_nacimiento").click()
    self.driver.find_element(By.ID, "fecha_nacimiento").click()
    self.driver.find_element(By.ID, "fecha_nacimiento").send_keys("2024-02-07")
    self.driver.find_element(By.ID, "genero").click()
    dropdown = self.driver.find_element(By.ID, "genero")
    dropdown.find_element(By.XPATH, "//option[. = 'Otro']").click()
    self.driver.find_element(By.ID, "tipo_vehiculo").click()
    dropdown = self.driver.find_element(By.ID, "tipo_vehiculo")
    dropdown.find_element(By.XPATH, "//option[. = 'Auto']").click()
    self.driver.find_element(By.ID, "btn-register").click()
    element = self.driver.find_element(By.ID, "btn-register")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    assert self.driver.switch_to.alert.text == "Entró a la función"
    assert self.driver.switch_to.alert.text == "<br />\n<b>Fatal error</b>:  Uncaught mysqli_sql_exception: Unknown database \'form_usuarios\' in C:\\xampp\\htdocs\\fernandezt1\\librerias\\conexion.php:3\nStack trace:\n#0 C:\\xampp\\htdocs\\fernandezt1\\librerias\\conexion.php(3): mysqli_connect(\'localhost\', \'root\', \'\', \'form_usuarios\')\n#1 C:\\xampp\\htdocs\\fernandezt1\\librerias\\funciones.php(3): require_once(\'C:\\\\xampp\\\\htdocs...\')\n#2 C:\\xampp\\htdocs\\fernandezt1\\insertar.php(3): require_once(\'C:\\\\xampp\\\\htdocs...\')\n#3 {main}\n  thrown in <b>C:\\xampp\\htdocs\\fernandezt1\\librerias\\conexion.php</b> on line <b>3</b><br />\n"
  
